"""API v1 라우터"""
from fastapi import APIRouter
from app.api.v1 import auth, recruitment, employee_photo, master_data, employee_education, employee_attendance_master, employee_annual_leave_balance, companies, system, attendance, attendance_standard, attendance_time_in_out, attendance_time_day, attendance_additional_ot, attendance_special_ot, attendance_payroll_bucket, payroll, payslip, reports, tax, chat, employee_types, employee_reference_items, major_codes, minor_codes, certificate_public, certificate_issue_delivery

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["인증"])
api_router.include_router(certificate_issue_delivery.router, prefix="/certificate-issues", tags=["기준정보"])
api_router.include_router(certificate_issue_delivery.router, prefix="/certificate-issue", tags=["기준정보"])
api_router.include_router(certificate_public.router, prefix="/public", tags=["공개·증명서전달"])
api_router.include_router(recruitment.router, prefix="/recruitment", tags=["채용"])
api_router.include_router(employee_photo.router, prefix="/employees", tags=["기준정보"])
api_router.include_router(employee_annual_leave_balance.router, prefix="/employees", tags=["기준정보"])
api_router.include_router(master_data.router, prefix="/employees", tags=["기준정보"])
api_router.include_router(employee_attendance_master.router, prefix="/employees", tags=["기준정보"])
api_router.include_router(employee_education.router, prefix="/employees", tags=["기준정보"])
api_router.include_router(companies.router, prefix="/companies", tags=["회사관리"])
api_router.include_router(employee_types.router, prefix="/employee-types", tags=["회사관리"])
api_router.include_router(employee_reference_items.router, prefix="/employee-reference-items", tags=["회사관리"])
api_router.include_router(major_codes.router, prefix="/major-codes", tags=["기준정보관리"])
api_router.include_router(minor_codes.router, prefix="/minor-codes", tags=["기준정보관리"])
api_router.include_router(system.router, prefix="/system", tags=["시스템관리"])
api_router.include_router(attendance.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_standard.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_time_in_out.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_time_day.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_additional_ot.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_special_ot.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(attendance_payroll_bucket.router, prefix="/attendance", tags=["근태관리"])
api_router.include_router(payroll.router, prefix="/payroll", tags=["급여"])
api_router.include_router(payslip.router, prefix="/payslip", tags=["급여명세서"])
api_router.include_router(reports.router, prefix="/reports", tags=["인사리포트"])
api_router.include_router(tax.router, prefix="/tax", tags=["세금"])
api_router.include_router(chat.router, prefix="/chat", tags=["AI 채팅"])
