-- 근태/OT/수당 집계 결과 저장 테이블 (create_all만으로 기존 DB에 반영 안 될 때 수동 실행)
-- psql -U postgres -d AI_HR -p 5433 -f migrations/add_attendance_payroll_bucket_aggregate.sql

CREATE TABLE IF NOT EXISTS attendance_payroll_bucket_aggregate (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  attendance_payment_period_id INTEGER REFERENCES attendance_payment_period(id) ON DELETE SET NULL,
  calendar_year INTEGER NOT NULL,
  calendar_month INTEGER NOT NULL,
  period_label VARCHAR(100) NOT NULL,
  income_ot_only BOOLEAN NOT NULL DEFAULT FALSE,
  pay_type VARCHAR(20),
  range_main_start DATE,
  range_main_end DATE,
  range_ot_start DATE,
  range_ot_end DATE,
  holiday_days INTEGER NOT NULL DEFAULT 0,
  days_worked INTEGER NOT NULL DEFAULT 0,
  working_minutes INTEGER NOT NULL DEFAULT 0,
  absent_minutes INTEGER NOT NULL DEFAULT 0,
  late_minutes INTEGER NOT NULL DEFAULT 0,
  early_minutes INTEGER NOT NULL DEFAULT 0,
  leave_with_pay_minutes INTEGER NOT NULL DEFAULT 0,
  leave_without_pay_minutes INTEGER NOT NULL DEFAULT 0,
  oth1 INTEGER NOT NULL DEFAULT 0,
  oth2 INTEGER NOT NULL DEFAULT 0,
  oth3 INTEGER NOT NULL DEFAULT 0,
  oth4 INTEGER NOT NULL DEFAULT 0,
  oth5 INTEGER NOT NULL DEFAULT 0,
  oth6 INTEGER NOT NULL DEFAULT 0,
  oth1_weekday INTEGER NOT NULL DEFAULT 0,
  oth1_holiday INTEGER NOT NULL DEFAULT 0,
  oth2_weekday INTEGER NOT NULL DEFAULT 0,
  oth2_holiday INTEGER NOT NULL DEFAULT 0,
  oth3_weekday INTEGER NOT NULL DEFAULT 0,
  oth3_holiday INTEGER NOT NULL DEFAULT 0,
  oth4_weekday INTEGER NOT NULL DEFAULT 0,
  oth4_holiday INTEGER NOT NULL DEFAULT 0,
  oth5_weekday INTEGER NOT NULL DEFAULT 0,
  oth5_holiday INTEGER NOT NULL DEFAULT 0,
  oth6_weekday INTEGER NOT NULL DEFAULT 0,
  oth6_holiday INTEGER NOT NULL DEFAULT 0,
  othb DOUBLE PRECISION NOT NULL DEFAULT 0,
  othb_weekday DOUBLE PRECISION NOT NULL DEFAULT 0,
  othb_holiday DOUBLE PRECISION NOT NULL DEFAULT 0,
  shift_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  food_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  special_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  fuel_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  standing_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  other_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  shift_ot_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  shift_over_ot_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  food_ot_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  food_over_ot_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  special_ot_allowance DOUBLE PRECISION NOT NULL DEFAULT 0,
  overtime_pay_local DOUBLE PRECISION NOT NULL DEFAULT 0,
  overtime_pay_local_weekday DOUBLE PRECISION NOT NULL DEFAULT 0,
  overtime_pay_local_holiday DOUBLE PRECISION NOT NULL DEFAULT 0,
  employee_number VARCHAR(64),
  employee_name VARCHAR(200),
  department VARCHAR(200),
  computed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT uq_att_payroll_bucket_agg_emp_period UNIQUE (
    employee_id,
    calendar_year,
    calendar_month,
    period_label,
    income_ot_only
  )
);

CREATE INDEX IF NOT EXISTS ix_att_payroll_bucket_agg_co_emp_y
  ON attendance_payroll_bucket_aggregate (company_id, employee_id, calendar_year);
CREATE INDEX IF NOT EXISTS ix_att_payroll_bucket_agg_co_ym
  ON attendance_payroll_bucket_aggregate (company_id, calendar_year, calendar_month);
