-- 직원 주소정보 (본적·현주소, 직원당 1행)
CREATE TABLE IF NOT EXISTS employee_addresses (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  perm_house_no_th VARCHAR(100),
  perm_house_no_en VARCHAR(100),
  perm_building_th VARCHAR(200),
  perm_building_en VARCHAR(200),
  perm_soi_th VARCHAR(200),
  perm_soi_en VARCHAR(200),
  perm_street_th TEXT,
  perm_street_en TEXT,
  perm_nationality VARCHAR(200),
  perm_zone VARCHAR(200),
  perm_province VARCHAR(200),
  perm_district VARCHAR(200),
  perm_sub_district VARCHAR(200),
  perm_postcode VARCHAR(30),
  perm_telephone VARCHAR(50),
  curr_house_no_th VARCHAR(100),
  curr_house_no_en VARCHAR(100),
  curr_building_th VARCHAR(200),
  curr_building_en VARCHAR(200),
  curr_soi_th VARCHAR(200),
  curr_soi_en VARCHAR(200),
  curr_street_th TEXT,
  curr_street_en TEXT,
  curr_nationality VARCHAR(200),
  curr_zone VARCHAR(200),
  curr_province VARCHAR(200),
  curr_district VARCHAR(200),
  curr_sub_district VARCHAR(200),
  curr_postcode VARCHAR(30),
  curr_telephone VARCHAR(50),
  CONSTRAINT uq_employee_addresses_employee_id UNIQUE (employee_id)
);

CREATE INDEX IF NOT EXISTS ix_employee_addresses_employee_id ON employee_addresses(employee_id);
