-- 기존 DB: 근태/OT/수당 집계 테이블에 평일·휴일 OT 분리 컬럼 추가
-- psql -U postgres -d AI_HR -p 5433 -f migrations/alter_attendance_payroll_bucket_aggregate_ot_weekday_holiday.sql

ALTER TABLE attendance_payroll_bucket_aggregate
  ADD COLUMN IF NOT EXISTS oth1_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth1_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth2_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth2_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth3_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth3_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth4_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth4_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth5_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth5_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth6_weekday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS oth6_holiday INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS othb_weekday DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS othb_holiday DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS overtime_pay_local_weekday DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS overtime_pay_local_holiday DOUBLE PRECISION NOT NULL DEFAULT 0;
